workflows:
  ios-pods-build-no-signing:
    name: iOS CocoaPods Build (No Signing)
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE_PATH: "src/CDGamez.xcworkspace"
        XCODE_SCHEME: "CDGamez"
      xcode: 15.0
    scripts:
      - name: Install CocoaPods & Generate .xcworkspace
        script: |
          cd src
          pod install
          cd ..

      - name: Build Archive (No Signing)
        script: |
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE_PATH" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA (No Signing)
        script: |
          xcodebuild -exportArchive \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$HOME/build/ipa"

    artifacts:
      - $HOME/build/ipa/*.ipa
      - $HOME/build/**/*.dSYM
