name: Build Unsigned IPA

on:
  push:
    branches:
      - main  # Or your desired branch (e.g., development, release)

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for Xcode builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install
      working-directory: ./src

    - name: List Xcode schemes
      run: |
        cd src
        xcodebuild -list -workspace CDGamez.xcworkspace # Or -project CDGamez.xcodeproj
        # Replace with your actual workspace or project file name.

    - name: Archive the project without code signing
      run: |
        cd src
        xcodebuild archive \
          -workspace CDGamez.xcworkspace \
          -scheme CDGamez \
          -archivePath build/unsigned.xcarchive \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Create ExportOptions.plist
      run: |
        cat > ExportOptions.plist <<EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>ad-hoc</string>
          <key>signingStyle</key>
          <string>manual</string>
          <key>compileBitcode</key>
          <false/>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>teamID</key>
          <string></string>
        </dict>
        </plist>
        EOL
      working-directory: ./src

    - name: Export unsigned IPA
      run: |
        cd src
        xcodebuild -exportArchive \
          -archivePath build/unsigned.xcarchive \
          -exportPath build/unsignedIPA \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload unsigned IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ipa
        path: src/build/unsignedIPA/*.ipa