name: Build and Export IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Import your code signing cert and provisioning profile
      - name: Import certificates and provisioning profile
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

      # Install dependencies (if using CocoaPods)
      - name: Install CocoaPods dependencies
        run: |
          cd src
          pod install

      # Build and archive the app with automatic signing enabled
      - name: Build and archive
        run: |
          xcodebuild archive \
            -workspace src/CDGamez.xcworkspace \
            -scheme CDGamez \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/CDGamez.xcarchive \
            -allowProvisioningUpdates

      # Export the IPA file
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/CDGamez.xcarchive \
            -exportOptionsPlist src/exportOptions.plist \
            -exportPath ${{ github.workspace }}/build/IPA \
            -allowProvisioningUpdates

      # Upload IPA as artifact (optional)
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: CDGamez-IPA
          path: build/IPA/*.ipa

      # Push IPA to a dedicated branch named IPA
      - name: Push IPA to IPA branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b IPA || git checkout IPA
          mkdir -p ipa_build
          cp build/IPA/*.ipa ipa_build/
          git add ipa_build/*.ipa
          git commit -m "Add latest IPA build"
          git push origin IPA --force
