name: Build Unsigned IPA

on:
  push:
    branches:
      - main  # Or your desired branch (e.g., development, release)

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods dependencies
        run: |
          gem install cocoapods
          pod install
        working-directory: ./src

      - name: Validate storyboard files exist and have correct case
        run: |
          if [ ! -f src/CDGamez/Base.lproj/Main.storyboard ]; then
            echo "Main.storyboard not found! Please check the path and case sensitivity."
            exit 1
          fi
          if [ ! -f src/CDGamez/Base.lproj/LaunchScreen.storyboard ]; then
            echo "LaunchScreen.storyboard not found! Please check the path and case sensitivity."
            exit 1
          fi

      - name: Clean build folder
        run: |
          cd src
          xcodebuild clean -workspace CDGamez.xcworkspace -scheme CDGamez

      - name: List Xcode schemes
        run: |
          cd src
          xcodebuild -list -workspace CDGamez.xcworkspace

      - name: Archive the project without code signing
        run: |
          cd src
          xcodebuild archive \
            -workspace CDGamez.xcworkspace \
            -scheme CDGamez \
            -archivePath build/unsigned.xcarchive \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create ExportOptions.plist
        run: |
          cat > src/ExportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string></string>
          </dict>
          </plist>
          EOL

      - name: Export unsigned IPA
        run: |
          cd src
          xcodebuild -exportArchive \
            -archivePath build/unsigned.xcarchive \
            -exportPath build/unsignedIPA \
            -exportOptionsPlist ExportOptions.plist

      - name: Verify IPA was created
        run: |
          if ls src/build/unsignedIPA/*.ipa 1> /dev/null 2>&1; then
            echo "IPA created successfully."
          else
            echo "IPA file was NOT created. Please check build logs for errors."
            exit 1
          fi

      - name: Upload unsigned IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: src/build/unsignedIPA/*.ipa
