name: Build Unsigned IPA

on:
  push:
    branches:
      - main  # Or your desired branch (e.g., development, release)

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for Xcode builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List Xcode schemes
      run: |
        cd src
        xcodebuild -list -project CDGamez.xcodeproj # Or -workspace your_workspace_name.xcworkspace
      # Replace 'your_project_name.xcodeproj' or 'your_workspace_name.xcworkspace' with your actual project/workspace file name.
      # This step helps you identify the correct scheme name.

    - name: Archive the project without code signing
      run: |
        cd src
        xcodebuild archive \
          -project CDGamez.xcodeproj \
          -scheme CDGamez \
          -archivePath build/unsigned.xcarchive \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -destination generic/platform=iOS \

    - name: Create the unsigned IPA
      run: |
        cd build/unsigned.xcarchive/Products
        mv Applications Payload
        zip -r unsigned.ipa Payload
      # This sequence of commands navigates to the archive, renames the 'Applications' folder to 'Payload', and zips it to create the IPA.

    - name: Upload unsigned IPA as artifact
      uses: actions/upload-artifact@v4  # Use v4 for better performance and artifact validation
      with:
        name: unsigned-ipa
        path: build/unsigned.ipa
      # This action uploads the generated unsigned.ipa file as a build artifact for download.
